### ISSUE TITLE
Build jekyll site for WHO/godata repo

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/language-godata#11]
Hey @aleksa-krolls , WHO already has a Github Pages site configured for https://github.com/WorldHealthOrganization/godata . It's currently live at https://worldhealthorganization.github.io/godata/ .

A repo can only have one Github Pages site live at the same time. Should I take down this old site and replace it with an empty Jekyll site? In the meantime, I'll set up the build to run locally and keep it on a branch.

**Comment by taylordowns2000** [comment]
Note that this is built and runs locally: https://github.com/WorldHealthOrganization/godata/tree/jekyll_site

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Amazing. Confirming the Github Pages URL will stay the same? (If yes, we can go live and I can migrate existing docs to this new site... if not, I will want to check-in with the Go.Data team before we publish.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , the Github Pages URL will stay the same, but the content hosted at that URL will be our new docs site, _not_ their existing, live-on-the-web, docs site. Let me know if you want to sync quickly on this, 2 min conversation would likely get us over the line!
